### PR TITLE
edits on problem sets + ps link fixes

### PR DESCRIPTION
**Pull request by aadsouza**
@wupeifan this is intended to replicate the PR from the source repo https://github.com/QuantEcon/lecture-source-ds/pull/321 (and also fixes a couple of links in the problem sets post migration to this repo). Could you please add in the new Q5 and Q6 in PS4? I couldn't find it in the new PS5 to move.

### CODE REVIEW

**Comment by wupeifan** [comment]
@aadsouza It was to move the first two commented questions in PS5 to PS4, replacing those questions.

**Comment by wupeifan** [comment]
Currently, there's no table of contents under /problem_set. Is it intentional?

**Comment by aadsouza** [comment]
@wupeifan are you talking about this issue https://github.com/QuantEcon/lecture-datascience.myst/issues/71?

**Comment by wupeifan** [comment]
@aadsouza probably related if you guys decide to hide everything under PS folder.
 Anyway, this PR should be safe to merge, just need someone else to check through...

**Comment by wupeifan** [comment]
I went through all those and I think they look fine (for now). Therefore, I'll merge it just to simplify the process.
There are a bunch of comments I got from the students last semester regarding the wordings of the PS. Probably will update soon next week.

**Pull request merged**
