### PR TITLE
Adding launch button settings and introducing qe-book-theme

### PR DESCRIPTION
**Pull request by AakashGfude**
The same as this PR https://github.com/QuantEcon/lecture-datascience.myst/pull/66

@arnavs @mmcky @jlperla @aadsouza let me know how the preview looks.

### CODE REVIEW

**Comment by aadsouza** [comment]
@AakashGfude on Safari, I have the `contents` sidebar with the qe book theme but it's only there at the top of the lectures. Once we scroll down to the middle of the lecture, it seems to disappear, leaving only a `back to top`. @arnavs if this is fine, @AakashGfude please ignore.

**Comment by aadsouza** [comment]
@WenxinM indeed, just tested on Chrome. It's the same for me as Safari - just shows at the top. On browsers in Windows, it doesn't show at all.

**Comment by aadsouza** [comment]
also entering dark mode with `change contrast` leaves non-heading and non-code text that was in black font as black. (@arnavs do we want to create a set of issues about these things?
Screen Shot 2021-05-07 at 9 58 31 PM
)

**Comment by aadsouza** [comment]
also, on Safari, `Download Notebook` gens a `.ipynb.html` file which is definitely a bug.

**Comment by WenxinM** [comment]
On windows, when downloading the notebooks from Chrome, it got the error `Failed - No file`.  When downloading from Microsoft Edge, it worked fine.

**Comment by aadsouza** [comment]
The `home` button takes us to the index of the introduction lectures, not the global home page.

**Comment by mmcky** [comment]
Adding scroll to the left hand menu bar prohibits it from being longer than a single screen length. So we decided to keep it fixed to the top so we don't have too many internal scroll mechanisms and enable the theme to be used with larger books that have may chapters.

**Comment by aadsouza** [comment]
also, images in the lectures under the theme are not contained in the margins
Screen Shot 2021-05-09 at 10 59 29 PM

**Comment by mmcky** [comment]
> also, images in the lectures under the theme are not contained in the margins
> Screen Shot 2021-05-09 at 10 59 29 PM

@aadsouza the new `jupyter-book` system actually works differently with regards to `image` sizes to the old `jupinx` system. `jupinx` relied on `html` to size the images where `jupyter-book` resizes the actual images. You will need to go through the migrated `myst` version and make adjustments to `figure` and `generated plots from code`

**Comment by aadsouza** [comment]
it seems to work fine on the vanilla theme though.
Screen Shot 2021-05-09 at 11 07 38 PM

**Comment by mmcky** [comment]
> @mmcky it seems to work fine on the vanilla theme though.
> Screen Shot 2021-05-09 at 11 07 38 PM

Hmm that is curious. Thanks @aadsouza (cc: @AakashGfude)

**Comment by aadsouza** [comment]
another thing quote blocks created using `>` do not seem to be different to regular paragraphs here. (see for example `the_index` lecture in `pandas`)

**Comment by AakashGfude** [comment]
Fixing bugs on this companion qe-book-theme PR: https://github.com/QuantEcon/quantecon-book-theme/pull/118

**Comment by AakashGfude** [comment]
@aadsouza @WenxinM @arnavs the latest netlify preview should have most of the issues fixed. Can you briefly go through and see if I missed anything?

P.S. The private field for the launcher will be implemented soon.

**Comment by aadsouza** [comment]
@AakashGfude latex does not appear to be stable. not particularly sure what triggers it. i refreshed the page once and it was fine, but navigated elsewhere and back after which it was gone again.
Screen Shot 2021-05-17 at 7 05 01 PM

**Comment by mmcky** [comment]
It might be helpful to have local contents listings in each `part` landing page?

https://60a314a302cc6d00aea6d4f8--nervous-villani-f8256d.netlify.app/python_fundamentals/index.html

**Comment by aadsouza** [comment]
i'll add them in @mmcky

**Comment by mmcky** [comment]
@AakashGfude should we set the `mathjax` to `v3` in https://github.com/QuantEcon/lecture-datascience.myst/blob/main/src/_config.yml

**Comment by aadsouza** [comment]
this one's probably minor, but there may be some formatting issues with the pdf

**Comment by mmcky** [comment]
>  but there may be some formatting issues with the pdf
@aadsouza the pdf generation for `lectures` is currently supported via `javascript` printing. We are working on supporting the `--individualpages` option to build `pdf` via LaTeX for individual pages via `jupyterbook-latex` but that is in work. We can look at building the book style (PDF) via LaTeX via jupyterbook-latex though.

**Comment by aadsouza** [comment]
do we want links to be the same font color as text?
Screen Shot 2021-05-17 at 7 21 46 PM

**Comment by aadsouza** [comment]
> another thing, quote blocks created using `>` do not seem to be different to regular paragraphs here. (see for example `the_index` lecture in `pandas`)

might still be an open issue

**Comment by mmcky** [comment]
> > another thing, quote blocks created using `>` do not seem to be different to regular paragraphs here. (see for example `the_index` lecture in `pandas`)
> 
> might still be an open issue

@AakashGfude does look like `quote block` styling needs to be added to `quantecon-book-theme`?

@aadsouza we have been switching most of these to use `note` admonitions such as

````
```{note}
<text>
```
````

which look quite nice. See https://jupyterbook.org/reference/cheatsheet.html?highlight=note%20admonition#admonitions

**Comment by AakashGfude** [comment]
> @AakashGfude should we set the `mathjax` to `v3` in https://github.com/QuantEcon/lecture-datascience.myst/blob/main/src/_config.yml

Done.

**Comment by AakashGfude** [comment]
> do we want links to be the same font color as text in dark mode?
> Screen Shot 2021-05-17 at 7 21 46 PM

Yeah, probably we should have a different one. Maybe greyish and underlined?

**Comment by aadsouza** [comment]
> > do we want links to be the same font color as text in dark mode?
> > Screen Shot 2021-05-17 at 7 21 46 PM
> 
> Yeah, probably we should have a different one. Maybe greyish and underlined?

i was thinking more like medium-light blue?..

**Comment by AakashGfude** [comment]
> i was thinking more like medium-light blue?..

Let me know the color code, and I will put that in. Will ask @drdrij as well for feedback, as he is the designer of the theme.

**Comment by aadsouza** [comment]
@AakashGfude either `#39ACE7` or `#3d8ed9`?

**Comment by WenxinM** [comment]
@AakashGfude In the new theme, we only have the `view source` option on the right corner which directs us to the myst repo. But we want to clone the `lecture-datascience.notebooks` repo. Do we want to add one button that leads to the notebooks repo, or should we update the _local installation_ lecture instead?

**Comment by aadsouza** [comment]
> @AakashGfude In the new theme, we only have the `view source` option on the right corner which directs us to the myst repo. But we want to clone the `lecture-datascience.notebooks` repo. Do we want to add one button that leads to the notebooks repo, or should we update the _local installation_ lecture instead?
The corresponding options given by the `clone` button for the new repo would be
[Open repository](https://github.com/QuantEcon/lecture-datascience.notebooks)
[Copy clone command to clipboard](git clone https://github.com/QuantEcon/lecture-datascience.notebooks)
[Open in GitHub Desktop](x-github-client://openRepo/https://github.com/QuantEcon/lecture-datascience.notebooks)

**Comment by AakashGfude** [comment]
> @AakashGfude In the new theme, we only have the `view source` option on the right corner which directs us to the myst repo. But we want to clone the `lecture-datascience.notebooks` repo. Do we want to add one button that leads to the notebooks repo, or should we update the _local installation_ lecture instead?

@WenxinM This will require design changes. We will ask @drdrij and @mmcky as well, for their inputs on design and any alternatives.

**Comment by mmcky** [comment]
@AakashGfude the switch to using `mathjax, v3, svg` is now working on my `safari` 👍

**Comment by AakashGfude** [comment]
I have done blockquote styling, updating mathjax to v3, link styling in dark-theme here: https://60a34489df2e554bab2fed24--nervous-villani-f8256d.netlify.app .

**Comment by WenxinM** [comment]
> I have done blockquote styling, updating mathjax to v3, link styling in dark-theme here: https://60a34489df2e554bab2fed24--nervous-villani-f8256d.netlify.app .

In the dark theme, the contrast for the images is a bit low in lecture `Introduction`, chapter `pandas`.

contrast

But images from other lectures look fine.

@AakashGfude

**Comment by aadsouza** [comment]
ooh we should probably add a background to those images or change them to a grey font

**Comment by mmcky** [comment]
@aadsouza @WenxinM love these ideas for theme improvements. But it would be best if you could please open an individual issue for each request on the theme repository: https://github.com/quantEcon/quantecon-book-theme. We can then evaluate each suggestion and get them implemented through future releases (cc: @AakashGfude @DrDrij). This will bring the best visibility for those working on the theme. 

Also the `dark theme` is pretty new and `experimental` so thanks for going through it and making suggestions.

**Comment by aadsouza** [comment]
@mmcky i've added one about the clone button and we've taken care of the images on our end. do you need issues for the stuff that @AakashGfude just worked on - quote blocks, link color in dark mode etc?

**Comment by mmcky** [comment]
> do you need issues for the stuff that @AakashGfude just worked on - quote blocks, link color in dark mode etc?

Not if they have been resolved already. But any that are open (or need input for style etc.) that would be awesome.

**Comment by AakashGfude** [comment]
> @AakashGfude either `#39ACE7` or `#3d8ed9`?

So, @drdrij suggested having white bold color instead of blue, as blue doesn't have enough contrast, and won't fulfill the purposes of dark theme completely. Is it ok with you @aadsouza ? the screenshot is in https://github.com/QuantEcon/quantecon-book-theme/pull/127

**Comment by aadsouza** [comment]
@AakashGfude looks good

**Comment by aadsouza** [comment]
@AakashGfude just checked the applied lin alg lectures in fundamentals and found this 
```
And, using the infinite sum formula from {doc}`Control Flow <../python_fundamentals/control_flow>` (i.e. $\sum_{t=0}^{\infty}\beta^t = (1 - \beta)^{-1}$)
```
Screen Shot 2021-05-18 at 10 50 04 PM

weirdly enough, it's fine in an earlier part of the lecture
```
In {doc}`control flow <../python_fundamentals/control_flow>`, we learned to value a stream of payoffs from a single
asset.
```
Screen Shot 2021-05-18 at 10 53 28 PM

this is a theme issue right?

**Comment by WenxinM** [comment]
> @AakashGfude just checked the applied lin alg lectures in fundamentals and found this
> 
> ```
> And, using the infinite sum formula from {doc}`Control Flow <../python_fundamentals/control_flow>` (i.e. $\sum_{t=0}^{\infty}\beta^t = (1 - \beta)^{-1}$)
> ```
> 
> Screen Shot 2021-05-18 at 10 50 04 PM
> 
> weirdly enough, it's fine in an earlier part of the lecture
> 
> ```
> In {doc}`control flow <../python_fundamentals/control_flow>`, we learned to value a stream of payoffs from a single
> asset.
> ```
> 
> Screen Shot 2021-05-18 at 10 53 28 PM
> 
> this is a theme issue right? (will submit an issue on `qe-book-theme` if you think it is)

There used to be an error here which has been fixed in the PR we merged yesterday. Any chance that the book developed here is based on the old main branch? @AakashGfude

**Comment by aadsouza** [comment]
> > @AakashGfude just checked the applied lin alg lectures in fundamentals and found this
> > ```
> > And, using the infinite sum formula from {doc}`Control Flow <../python_fundamentals/control_flow>` (i.e. $\sum_{t=0}^{\infty}\beta^t = (1 - \beta)^{-1}$)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Screen Shot 2021-05-18 at 10 50 04 PM
> > weirdly enough, it's fine in an earlier part of the lecture
> > ```
> > In {doc}`control flow <../python_fundamentals/control_flow>`, we learned to value a stream of payoffs from a single
> > asset.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Screen Shot 2021-05-18 at 10 53 28 PM
> > this is a theme issue right? (will submit an issue on `qe-book-theme` if you think it is)
> 
> There used to be an error here which has been fixed in the PR we merged yesterday. Any chance that the book developed here is based on the old main branch? @AakashGfude

@AakashGfude oops never mind. i think what happened is that we merged a pr that fixed this issue after you had triggered the netlify preview

**Comment by AakashGfude** [comment]
> this is a theme issue right? (will submit an issue on `qe-book-theme` if you think it is)

actually the problem is in the source file. the source file has the following text 
``
{doc}`../python_fundamentals/control_flow <../python_fundamentals/control_flow>`
``
changing it to 

``
{doc}`control flow <../python_fundamentals/control_flow>`
``
will help

**Comment by mmcky** [comment]
@DrDrij I have just triggered a rebuild here and it is pulling from `jupyterlab` branch in `quantecon-book-theme` so you can preview the adjustments for the `launch buttons` work.

**Comment by mmcky** [comment]
Nice work @DrDrij I like the change to integrate them into the one button. Looking really nice!

Screen Shot 2021-05-26 at 2 33 52 pm

**Comment by mmcky** [comment]
- [ ] merge https://github.com/QuantEcon/quantecon-book-theme/pull/130 and release `quantecon-book-theme=0.3.0`
- [ ] Get feedback from datascience team about prototype (cc: @arnavs @jlperla) with the preview build: https://60adcf617687443d6d209d10--nervous-villani-f8256d.netlify.app

**Comment by mmcky** [comment]
@aadsouza are you adding a `tableofcontents` directive to each `part` page?

**Comment by aadsouza** [comment]
> @aadsouza are you adding a `tableofcontents` directive to each `part` page?

@mmcky yeah it's on the main branch. going to merge this one now.

**Pull request merged**
