### PR TITLE
add ahs files

### PR DESCRIPTION
**Pull request by wupeifan**
solves https://github.com/QuantEcon/lecture-datascience.myst/issues/81

### CODE REVIEW

**Comment by aadsouza** [comment]
do we need `ahs-eval.csv` as well?

**Comment by wupeifan** [comment]
I don't think we've ever used that file. At least not in PS8. Where exactly does that filename appear?

**Comment by aadsouza** [comment]
from `prep-ahs.R`:
```
traindf <- df[traini,]
evaldf  <- df[-traini,]

write.csv(traindf,"ahs-train.csv", row.names=FALSE)
write.csv(evaldf, "ahs-eval.csv", row.names=FALSE)
```

**Comment by wupeifan** [comment]
I see, the test data. Let me see whether I have that somewhere.

**Comment by wupeifan** [comment]
It's because we never assigned that problem set lol.

**Comment by wupeifan** [comment]
@aadsouza  I remember the issue now: the eval file was relatively large so it actually blows up the limited disk space we have on ubc.syzygy.ca. Therefore I changed these two files just to make them toy examples: basically, the original train file has 2500 observations, and I split them into 2, with 2000 remaining in the training file and the rest goes to the evaluation file. At least this should be sufficient for this PS.

**Comment by aadsouza** [comment]
perfect, then i think we should be good to merge

**Pull request merged**
