### PR TITLE
fix merge, groupby files

### PR DESCRIPTION
**Pull request by Alim-faraji**
`merge.md`: `goodreads_books.csv.zip` contained two csv file. I replaced it with the right dataset. 

`groupby.md`: I added a line `air_dec.Date = pd.to_datetime(air_dec.Date)` after reading the data which solved the problem.

### CODE REVIEW

**Comment by wupeifan** [comment]
Pandas should parse the date line as in the datetime format. While a solution like what you have above is totally fine, out of curiosity, can you diagnose what exactly happens to that column?

**Comment by wupeifan** [comment]
Actually, can you try
```
air_dec = pd.read_csv("filename", parse_dates = ['Date'])
```

**Comment by Alim-faraji** [comment]
I'm not sure exactly what happens with that column. But this is the error I get:

**Comment by wupeifan** [comment]
The error is because pandas didn't parse the dates as datetime format, so they cannot be treated as indices. That probably indicates that the column is not clean. Anyway.
Does the new fix work?

**Comment by Alim-faraji** [comment]
Yes, it works. The `groupby.md` lecture should work just fine. But `merge.md` needs a file that is not uploaded yet. after merging this PR, I publish it to `gh-pages`, and then it should be fine.

**Comment by wupeifan** [comment]
OK. Squash and merge this, push the file, tag a new release then. Thanks

**Pull request merged**
