### PR TITLE
Adding launch button settings

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR should be merged only after https://github.com/QuantEcon/quantecon-book-theme/pull/95 , which will then provide binder, jupyterhub, colab links.

Have also done few changes in https://github.com/QuantEcon/quantecon-book-theme/pull/95 , to show all the page links in the left sidebar.

The page looks like this:

Screen Shot 2021-04-14 at 7 36 41 pm

### CODE REVIEW

**Comment by arnavs** [comment]
Hey @aadsouza any idea why the TOC or any links are not showing up on the homepage?

**Comment by WenxinM** [comment]
Hey @AakashGfude, we currently have two open issues related to the book theme. It could be solved after merging this PR. One is that we have some unsupported theme options:
`WARNING: unsupported theme option 'header_organisation_url' given`
`WARNING: unsupported theme option 'header_organisation' given`
`WARNING: unsupported theme option 'nb_repository_url' given`
`WARNING: unsupported theme option 'twitter' given`
`WARNING: unsupported theme option 'twitter_logo_url' given`
`WARNING: unsupported theme option 'og_logo_url' given`
`WARNING: unsupported theme option 'description' given`
`WARNING: unsupported theme option 'keywords' given`

**Comment by AakashGfude** [comment]
> Hey @AakashGfude any idea why the TOC or any links are not showing up on the homepage?

Because the homepage does not seem to contain the text to show it.

**Comment by AakashGfude** [comment]
> Hey @AakashGfude, we currently have two open issues related to the book theme. It could be solved after merging this PR. 

Hey @WenxinM , can you share with us the links to those issues. Will see what exact resolution they need.

**Comment by WenxinM** [comment]
> > Hey @AakashGfude, we currently have two open issues related to the book theme. It could be solved after merging this PR.
> 
> Hey @WenxinM , can you share with us the links to those issues. Will see what exact resolution they need.

1. Warnings on book themes: #12 
2. Screenshots about launching etc.: #46

**Comment by aadsouza** [comment]
@AakashGfude does your new left side bar with page links render on the homepage as well? @arnavs @WenxinM

**Comment by AakashGfude** [comment]
> @AakashGfude The sidebar on the left does not appear to work for the homepage. Was this expected? In the vanilla theme it renders fine - thereby allowing users to access the lectures of interest. The alternative would just be to add in the links to the introductions of every section on the homepage. @arnavs @WenxinM

@aadsouza Sorry, the website in the netlify preview shown in this PR, would be broken as it is using the master branch of `quantecon-book-theme`, while the necessary changes are in https://github.com/QuantEcon/quantecon-book-theme/pull/95. I should probably mark this PR as a draft for now, till I make a working preview here.

**Comment by aadsouza** [comment]
> > @AakashGfude The sidebar on the left does not appear to work for the homepage. Was this expected? In the vanilla theme it renders fine - thereby allowing users to access the lectures of interest. The alternative would just be to add in the links to the introductions of every section on the homepage. @arnavs @WenxinM
> 
> @aadsouza Sorry, the website in the netlify preview shown in this PR, would be broken as it is using the master branch of `quantecon-book-theme`, while the necessary changes are in [QuantEcon/quantecon-book-theme#95](https://github.com/QuantEcon/quantecon-book-theme/pull/95). I should probably mark this PR as a draft for now, till I make a working preview here.

@AakashGfude I see. Thanks for the clarification.

**Comment by AakashGfude** [comment]
@mmcky @jlperla @arnavs , the launch buttons in the latest netlify deployment, should be working now. 

The only catch was that the notebooks for datascience in https://github.com/QuantEcon/lecture-datascience.notebooks is nested inside a `jupyter` folder. So, had to use `https://github.com/QuantEcon/lecture-datascience.notebooks/jupyter` as the `nb_repository_url` in the config.
For these cases, we can either do the same like I have done, or create a new variable like `nb_repository_subpath` or something, to store `jupyter/` path.

**Comment by mmcky** [comment]
thanks @AakashGfude

I think we should be ok with adopting a `notebook` repository that doesn't contain sub-folders like `jupyter` so we just sync the notebooks into the `lecture-datascience.notbooks` at the root level (in the folder structure of the project) to serve them to `binder` etc. 

@jlperla do you need a `jupyter` sub-folder for cloning purposes for jupyterhub?

**Comment by mmcky** [comment]
@AakashGfude just did a quick review of the implementation in `quantecon-book-theme`. Thanks for putting this together as it is great to see how this works. 

I think it would be better to:

1. if one server is specified then just route to the service via the "play" icon
2. if multiple servers are specified then open the model (that includes a launch button below the setting options)

I don't find the "settings" icon very intuitive in this context as they don't visually seemed linked.

**Comment by jlperla** [comment]
Thanks guys. Are you saying that it is hard to support the jupyter subfolder but otherwise the subfolder structure is fine?  Then no problem @arnavs

We can just put the stripped out python files in the same directory. ddoes that make sense arnav?

**Comment by jlperla** [comment]
The other thing is that I think we should remove the jupyterhub from the drop down until we can support multiple ones. Otherwise it would be very confusing (and not really useful until the fall)

**Comment by mmcky** [comment]
@jlperla @arnavs if you have a good reason to keep using a `jupyter` folder. That is fine - we just need to add some `config` to the theme for the link generation for binder, colab etc.

**Comment by arnavs** [comment]
Sorry, forgot to post here. No reason to keep using the `jupyter` folder. I've removed it. But we do need subfolders like `applications/`, `intro`/ etc.

**Comment by AakashGfude** [comment]
> Sorry, forgot to post here. No reason to keep using the `jupyter` folder. I've removed it. But we do need subfolders like `applications/`, `intro`/ etc.

Yes,  that works. Only the top folder was the issue.

**Comment by AakashGfude** [comment]
> The other thing is that I think we should remove the jupyterhub from the drop down until we can support multiple ones. Otherwise it would be very confusing (and not really useful until the fall)

Sure, I will just remove the entry from the `_config.yml` for now, for datascience.

**Comment by aadsouza** [comment]
@AakashGfude @arnavs is this good to merge?

**Comment by AakashGfude** [comment]
Hey @aadsouza, sorry it was not ready to be merged yet. Two things were blocking it:

1) first we need to merge https://github.com/QuantEcon/quantecon-book-theme/pull/95 (pretty easy)
2) execution atm is turned off in this PR. Reason: A piece of interactive python code is breaking JS. we need to fix that first,  then merge. (not so easy)

I will revert the merge for now. And start finishing the above points.

**Pull request merged**
