### PR TITLE
`src` to `lectures` prep

### PR DESCRIPTION
**Pull request by aadsouza**

### CODE REVIEW

**Comment by aadsouza** [comment]
@arnavs @mmcky should be good to go now. this addresses #120

**Comment by WenxinM** [comment]
there is one more edit needed in lecture problem-set 5:
````
```{code-cell} python
url = "https://datascience.quantecon.org/assets/data/state_unemployment.csv"
unemp_raw = pd.read_csv(url, parse_dates=["Date"])
```
````

- [ ] download and upload the CSV file to the problem set fold
- [ ] update the link

These can be easily changed after the PR is merged. The reason why we didn't do it now is that the changes will create conflict in this PR.

**Comment by mmcky** [comment]
@aadsouza you should remove `lectures/_build` as that doesn't need to be committed (and add it to `.gitignore` as `_build`)

**Comment by mmcky** [comment]
@aadsouza I am surprised there aren't more:

```
src/python_fundamentals/collections.md → lectures/python_fundamentals/collections.md
```

and it looks like `git` has setup new files? 

Did you use:

```
git mv src lectures
```

**Comment by aadsouza** [comment]
> @aadsouza you should remove `lectures/_build` as that doesn't need to be committed (and add it to `.gitignore` as `_build`)
> 
> ```
> git rm -r lectures/_build
> ```

interesting, how did that stuff end up being pushed. `lectures/_build` was in the `.gitignore`. will take out the stuff that's in the directory now. @WenxinM was the directory name changed using `git-mv`?

**Comment by aadsouza** [comment]
> @aadsouza I am surprised there aren't more:
> 
> ```
> src/python_fundamentals/collections.md → lectures/python_fundamentals/collections.md
> ```
> 
> and it looks like `git` has setup new files?
> 
> Did you use:
> 
> ```
> git mv src lectures
> ```

@mmcky `src/python_fundamentals/collections.md → lectures/python_fundamentals/collections.md` is in the diff as are most of the lectures. the diff is really messy with all the build stuff. taking that out should give us a clearer idea about whats going on

**Comment by aadsouza** [comment]
looks more reasonable now

**Comment by aadsouza** [comment]
going to merge.🤞

**Pull request merged**
