### PR TITLE
Fix figure paths to local _static references

### PR DESCRIPTION
**Pull request by wupeifan**

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @wupeifan

**Comment by mmcky** [comment]
There still seems to be a few other documents such as

```
lectures//scientific/applied_linalg.md:```{figure} https://raw.githubusercontent.com/QuantEcon/lecture-datascience.myst/main/lectures/_static/vector.png
```

**Comment by wupeifan** [comment]
Alright, let me check those. Might be because of case-sensitive searches...

**Comment by wupeifan** [comment]
There are two links with `https://datascience.quantecon.org/assets/_static` which are not included in the current folder. Should I update those files? @mmcky

**Comment by mmcky** [comment]
I think the last pattern is:

```
.//problem_sets/problem_set_6.md:```{figure} https://datascience.quantecon.org/assets/_static/groupby_files/groupby_cohort_analysis_exercise_output.png
```

**Comment by wupeifan** [comment]
Then there are also some other files under `https://datascience.quantecon.org/assets/` that we need to download and update here, probably...

**Comment by mmcky** [comment]
> Then there are also some other files under `https://datascience.quantecon.org/assets/` that we need to download and update here, probably...

Indeed. There are two main types it seem: `data` and `figures`. I see how `data` works but not sure why some `figures` are pulling from `assets` rather than `_static`.

**Comment by mmcky** [comment]
@wupeifan I will merge this -- and maybe we can open an issue for the other items above.

**Pull request merged**
