### PR TITLE
MAINT: upgrade jupyter-book and quantecon-book-theme

### PR DESCRIPTION
**Pull request by mmcky**
Upgrades

- `jupyter-book==0.12.1`
- `quantecon-book-theme==0.3.0`

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] check if `plotly` issues is resolved

https://datascience.quantecon.org/applications/regression.html.
https://datascience.quantecon.org/applications/regression.html#regression-trees

**Comment by mmcky** [comment]
@AakashGfude the `plotly` figures are still missing after the software upgrade.

**Comment by AakashGfude** [comment]
> https://619737f705967375a9f487aa--nervous-villani-f8256d.netlify.app

@mmcky the plotly figure seems to be present in https://619737f705967375a9f487aa--nervous-villani-f8256d.netlify.app/applications/regression.html#random-forests

**Comment by mmcky** [comment]
Ah ha -- so it takes a bit of time for the objects to load but I see them too.

**Pull request merged**
