### PR TITLE
MAINT: update config for jb==0.15.1

### PR DESCRIPTION
**Pull request by mmcky**
This PR adjusts the config for the project due to some changes in `jupyter-book`

### CODE REVIEW

**Comment by mmcky** [comment]
Issues that need to be resolved

- [ ] /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/lectures/applications/maps.md:466: WARNING: skipping unknown output mime type: application/vnd.bokehjs_load.v0+json [mystnb.unknown_mime_type]
- [ ] /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/lectures/applications/maps.md:480: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
- [ ] /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/lectures/applications/recidivism.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
  /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/lectures/applications/recidivism.md: WARNING: Notebook exception traceback saved in: /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/_build/html/reports/applications/recidivism.err.log [mystnb.exec]

**Comment by mmcky** [comment]
@doctor-phil will need to think about the first two. Not sure what is driving that.

**Comment by mmcky** [comment]
- [ ] check if [ecda245](https://github.com/QuantEcon/lecture-datascience.myst/pull/219/commits/ecda2452df99e0873613d7de6d59f2518ffb90c6) fixes the execution error once completed

**Comment by mmcky** [comment]
The following error is being issued:

```
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
```

from

```python
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plots illustrating regularization parameter choice
scores=lasso_mod.scores_[1.0].mean(axis=0)
logpenalties=np.log(lasso_mod.Cs_)
nnonzero=(np.abs(lasso_mod.coefs_paths_[1.0])>1e-6).sum(axis=2).mean(axis=0)
colors=plt.rcParams["axes.prop_cycle"].by_key()["color"]
fig, ax1 = plt.subplots()
ax1.plot(logpenalties,scores, color=colors[0])
ax1.set_ylabel("CV log likelihood", color=colors[0])
ax1.set_xlabel("-log(penalty)")
ax1.tick_params('y', colors=colors[0])
ax2 = ax1.twinx()
ax2.plot(logpenalties,nnonzero, color=colors[1])
ax2.set_ylabel("nonzero coefficients", color=colors[1])
ax2.tick_params('y', colors=colors[1])
ax2.grid(b=None);
------------------
```

for `recidivism`

**Comment by mmcky** [comment]
- [x] suppressing the bokeh warning based on https://github.com/executablebooks/jupyter-book/issues/1950

**Comment by mmcky** [comment]
- [ ] update to use `jupyter-book build -nW --keep-going lectures`

**Comment by mmcky** [comment]
@doctor-phil I have forced a full rebuild as a test (without the cache) to see if that uses the latest code in that cell.

**Comment by mmcky** [comment]
@doctor-phil I have an issue with `Fiona` when trying to install this environment. 

Perhaps #200 needs to be done :-)

**Comment by doctor-phil** [comment]
@mmcky 2/3 windows devices that I have tried to build on have had errors involving `Fiona` or `Geopandas`. That was before the current environment build failures involving the mysterious Python 3.11 error

**Comment by doctor-phil** [comment]
> The following error is being issued:
> 
> ```
> ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
> ```
> 
> from
> 
> ```python
> nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
> ------------------
> # plots illustrating regularization parameter choice
> scores=lasso_mod.scores_[1.0].mean(axis=0)
> logpenalties=np.log(lasso_mod.Cs_)
> nnonzero=(np.abs(lasso_mod.coefs_paths_[1.0])>1e-6).sum(axis=2).mean(axis=0)
> colors=plt.rcParams["axes.prop_cycle"].by_key()["color"]
> fig, ax1 = plt.subplots()
> ax1.plot(logpenalties,scores, color=colors[0])
> ax1.set_ylabel("CV log likelihood", color=colors[0])
> ax1.set_xlabel("-log(penalty)")
> ax1.tick_params('y', colors=colors[0])
> ax2 = ax1.twinx()
> ax2.plot(logpenalties,nnonzero, color=colors[1])
> ax2.set_ylabel("nonzero coefficients", color=colors[1])
> ax2.tick_params('y', colors=colors[1])
> ax2.grid(b=None);
> ------------------
> ```
> 
> for `recidivism`

@mmcky I changed the code on this branch to remove the depreciated keyword argument `b=None`. This error should no longer appear, we'll see what happens

**Pull request merged**
