### PR TITLE
 TEST: private-jupyterlab branch of quantecon-book-theme

### PR DESCRIPTION
**Pull request by AakashGfude**
Testing `private-jupyerlab` branch of qe-book-theme :https://github.com/QuantEcon/quantecon-book-theme/tree/private-jupyterlab

You can test this using: `https://pims.syzygy.ca` for `private`

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude anything I should pay particular attention to? Looks pretty good -- similar to `jupyterlab` branch -- has this got the `branchname` addition?

**Comment by AakashGfude** [comment]
> @AakashGfude anything I should pay particular attention to? Looks pretty good -- similar to `jupyterlab` branch -- has this got the `branchname` addition?

yes, it has. So should work with this repo

**Comment by mmcky** [comment]
@AakashGfude I am getting `undefined` on this PR for `binderhub`

**Comment by mmcky** [comment]
@AakashGfude I tried this using `pims.syzygy.ca` but looks like you need the `https://`

Minor thing but maybe we should accept both?

**Comment by AakashGfude** [comment]
> Minor thing but maybe we should accept both?

have added this feature in the branch.

> @AakashGfude I am getting `undefined` on this PR for `binderhub`

working on making the button disabled, when no text is input in the private field.

**Comment by AakashGfude** [comment]
> > Minor thing but maybe we should accept both?
> 
> have added this feature in the branch.
> 
> > @AakashGfude I am getting `undefined` on this PR for `binderhub`
> 
> working on making the button disabled, when no text is input in the private field. Ohh no, binderhub. looking at that,

**Comment by mmcky** [comment]
> working on making the button disabled, when no text is input in the private field.

@AakashGfude not sure I follow. I had `BinderHub` selected and then clicked Launch and it ended up at a `404`

**Comment by mmcky** [comment]
thanks @AakashGfude closing this as it has served its purpose as a test case

**Pull request closed without merging**
