### PR TITLE
MAINT: Error on Warning and Associated Fixes to get Warning Free

### PR DESCRIPTION
**Pull request by mmcky**
This adds `-W --keep-going` to build scripts via `github actions` to increase robustness for publishing workflows

**Note:** Requires `jupyter-book>0.11`

- [x] `orphans` will be resolved by #133 + `jupyter-book>=0.11`
- [x] execution issue for `heterogenity` lecture
- [x] theme options was an old issue relating to `sphinx-book-theme`
- [x] incorrect link is updated

@aadsouza can you list any warnings that are still not resolved?

### CODE REVIEW

**Comment by aadsouza** [comment]
copying my previous message. might be outdated. will take a look at the new stuff in the interim to see if there's anything else

Just went through the list of warnings. I think we can summarize them down to:
- need orphan-esque tag to allow PSes and contributors/projects to not be in toc (issue 71)
- theme options that should be suppressed once the theme is merged
-
```
/home/runner/work/lecture-datascience.myst/lecture-datascience.myst/src/theme/projects_hust.md:14: WARNING: 'myst' reference target not found: "http://english.hust.edu.cn/"
```
which might be because of `https` vs `http` but not :100: sure

**Comment by mmcky** [comment]
> * need orphan-esque tag to allow PSes and contributors/projects to not be in toc (issue 71)

This is addressed by https://github.com/QuantEcon/lecture-datascience.myst/pull/133

**Comment by mmcky** [comment]
> ```
> /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/src/theme/projects_hust.md:14: WARNING: 'myst' reference target not found: "http://english.hust.edu.cn/"
> ```

@aadsouza can you fix this via PR?

**Comment by mmcky** [comment]
> * theme options that should be suppressed once the theme is merged

@aadsouza not sure what you mean here?

**Comment by aadsouza** [comment]
> > ```
> > /home/runner/work/lecture-datascience.myst/lecture-datascience.myst/src/theme/projects_hust.md:14: WARNING: 'myst' reference target not found: "http://english.hust.edu.cn/"
> > ```
> 
> 
> @aadsouza can you fix this via PR?

there does not exist a `https://english.hust.edu.cn`. it needs to be `http`.

**Comment by aadsouza** [comment]
> > * theme options that should be suppressed once the theme is merged
> 
> @aadsouza not sure what you mean here?

there was initially some stuff where the vanilla theme for instance had no idea what `nb_repo` etc. meant. i'd expect that to be fixed now that we have merged `qe-book-theme` in.

**Comment by mmcky** [comment]
The execution report from the execution failure [heterogeneity] is now uploaded as an artifact

While the formatting needs to be `tidied` up it gives an idea of what is breaking. 

[heterogeneity.log](https://github.com/QuantEcon/lecture-datascience.myst/files/6581871/heterogeneity.log)

**Comment by mmcky** [comment]
> there does not exist a `https://english.hust.edu.cn`. it needs to be `http`.

It was `http` but it had `"` in the link 905f8b6

**Comment by mmcky** [comment]
@aadsouza I don't think 46ee1fb is the issue. Probably need to check what encoding is being used on the source file

https://stackoverflow.com/questions/44659851/unicodedecodeerror-utf-8-codec-cant-decode-byte-0x8b-in-position-1-invalid/44660123

**Comment by aadsouza** [comment]
@mmcky i had changed the `gz` file to a regular `csv` with this https://github.com/QuantEcon/lecture-datascience.myst/pull/132/commits/849b7ddd614319693db41620b27508811d0f0ae5

**Comment by aadsouza** [comment]
just checked the log
```
------------------
url = "https://github.com/QuantEcon/lecture-datascience.myst/blob/main/lectures/applications/Triyana_2016_price_women_clean.csv.gz?raw=true"
df = pd.read_csv(url)
df.describe()
------------------
```
it wasn't using the revised one that had been committed

**Comment by aadsouza** [comment]
@mmcky yeah this should've worked, if it built ex-post delta

**Comment by mmcky** [comment]
> @mmcky yeah this should've worked, if it built ex-post delta

Ah ha -- it is working just failuring due to the final `warnings` that need `jupyter-book==0.11`

**Comment by mmcky** [comment]
Great -- we will of course need that `reference` to be reverted so it pulls the csv from `raw/main` 👍

**Comment by mmcky** [comment]
- [ ] merge when `jupyter-book==0.11` is released

**Comment by mmcky** [comment]
thanks @aadsouza looking good.

**Comment by aadsouza** [comment]
warning free :grin: 🥳

**Comment by aadsouza** [comment]
merging. thanks @mmcky

**Comment by mmcky** [comment]
nice work @aadsouza -- great to be warning free now.

**Pull request merged**
