### PR TITLE
FIX: Move /assets/ to jupyter-book build system to support problem sets

### LINKED ISSUE #163: Migrate assets for data Downloads
> Then there are also some other files under https://datascience.quantecon.org/assets/ that we need to download and update here, probably...

Indeed. There are two main types it seem: data and figures. I see how data works but not sure why some figures are pulling from assets rather than _static.

### PR DESCRIPTION
**Pull request by mmcky**
fixes #163

### CODE REVIEW

**Comment by mmcky** [comment]
**Note:** the links to download this data won't actually work until we deploy live as I have changed them from:

```
/assets/
```

to 

```
/_data/
```

**Comment by mmcky** [comment]
The above change makes testing hard so i have retained the use of `assets/data` as it will pull it in from the current live site.

**Comment by mmcky** [comment]
The assets are now populating `/assets/data/` from `lectures/_data`

https://60d176afbc28c937000ff585--nervous-villani-f8256d.netlify.app/assets/data/canada_census.csv

**Comment by jlperla** [comment]
If this is the same way you are doing it for python, that is good enough for me

**Comment by mmcky** [comment]
@jlperla we don't have any instances of serving `data` on any of the `python` projects.

**Comment by jlperla** [comment]
Ok, but you have static images? It seems like it should be handled in the
identical way?

**Comment by mmcky** [comment]
> Ok, but you have static images? It seems like it should be handled in the identical way?
> […](#)

Yes -- we pull those from the website with links auto generated by `sphinx-tojupyter`. We don't have any `data` assets that aren't used by `jupyter-book` in any way but are referenced by a lecture such as in the code cell of `problem_set_6.md` which uses `pandas` to pull in `csv` data

**Comment by jlperla** [comment]
> > Ok, but you have static images? It seems like it should be handled in the identical way?
> > […](#)
> 
> Yes -- we pull those from the website with links auto generated by `sphinx-tojupyter`. We don't have any `data` assets that aren't used by `jupyter-book` in any way but are referenced by a lecture such as in the code cell of `problem_set_6.md` which uses `pandas` to pull in `csv` data

I think we are just going to have to follow your lead. Whatever you want us to do to get things as consistent as possible with the python for all images etc. So whatever you want Matt, I don't think other people can design the right way to manage assets. As long as it is as easy to maintain as possible, great... No need for my code review on infrastructure.

But also just to verify, part of this is also fixing thE fact that the static images/etc wilk be managed intthe same way as the python lectures? Again, consistent and easy maintenance is all I care about

**Comment by mmcky** [comment]
The only other approach is to use a `download` directive that would `copy` assets in a similar way to `figure` directives to ` _downloads` folder but this will insert a link into your `md` file for users to actually download the data. This could be a way to do it but the `code-cell` will fetch the data from the website location directly. So I think this approach is the best so it isn't confusing to users (that try downloading the data when that isn't needed). 

Ultimately it would be nice to have a directive for this purpose such as:

````
```{dependency} _data/<some data>
outdir: _data
```
````

that would then copy this to some location such as `_data`

Then you would insert these in a `md` file to inform sphinx that file needs some data file to run. 

---

> Whatever you want us to do to get things as consistent as possible with the python for all images etc. 

This PR isn't about the images issue. That was just updating `publish.yml` so `lectures-datascience.notebook` doesn't contain unused `_build` artifacts: `_static` and `_panels_static`

**Comment by mmcky** [comment]
> As long as it is as easy to maintain as possible

This is definitely my aim 👍 I think moving everything to `github` is a big step forward. Then we can iterate again to push for greater simplification.

**Comment by Alim-faraji** [comment]
Figures doesn't seem to link to the right file. I think it is partly on how the links are generated from `.md` files. For example [here](https://github.com/QuantEcon/lecture-datascience.notebooks/blob/main/problem_sets/problem_set_6.ipynb): Figure points to this link: `https://datascience.quantecon.org/assets/https://datascience.quantecon.org/_static/pandas_files/canada_censusdivisions_map.png`. 
The figures in the `_static` doesn't seem to generate the right link, [here](https://github.com/QuantEcon/lecture-datascience.notebooks/blob/main/scientific/applied_linalg.ipynb) you see this link: `https://datascience.quantecon.org/_static/vector.png`. Or maybe these ones work when we deployed the site?

**Comment by jlperla** [comment]
Thanks for the careful testing Alim!

**Comment by wupeifan** [comment]
@Alim-faraji  Because that's something we didn't change yet. Could you please change those links similar to what is done here https://github.com/QuantEcon/lecture-datascience.myst/pull/161 ? Thanks

**Comment by Alim-faraji** [comment]
Sorry, The links to download the notebooks in the toolbar were pointed to the previous notebooks. It was a little confusing, and I think I was looking at the previous notebook repo. The new ones doesn't have this problem (relative and absolute paths).

**Comment by Alim-faraji** [comment]
The issue rn is this:
The `.md` file [here ](https://raw.githubusercontent.com/QuantEcon/lecture-datascience.myst/fix-163/lectures/problem_sets/problem_set_6.md)points to: ` ../_static/canada_censusdivisions_map.png` (or `https://datascience.quantecon.org/_static/canada_censusdivisions_map.png` in absolute path terms when downloading the notebook), but in the html [file](https://60d176afbc28c937000ff585--nervous-villani-f8256d.netlify.app/problem_sets/problem_set_6), it points to `https://60d176afbc28c937000ff585--nervous-villani-f8256d.netlify.app/_images/canada_censusdivisions_map.png`.

**Comment by jlperla** [comment]
> Sorry, The links to download the notebooks in the toolbar were pointed to the previous notebooks. It was a little confusing, and I think I was looking at the previous notebook repo. The new ones doesn't have this problem (relative and absolute paths).

Is this a bug? Is there a url which is incorrect somewhere?

**Comment by Alim-faraji** [comment]
I'm not sure really. But if you launch, for example, [this page](https://60d176afbc28c937000ff585--nervous-villani-f8256d.netlify.app/problem_sets/problem_set_6) with binder, it launches an outdated notebook instead.

**Comment by Alim-faraji** [comment]
> > Sorry, The links to download the notebooks in the toolbar were pointed to the previous notebooks. It was a little confusing, and I think I was looking at the previous notebook repo. The new ones doesn't have this problem (relative and absolute paths).
> 
> Is this a bug? Is there a url which is incorrect somewhere?

I'm not sure really. But if you launch, for example, [this page](https://60d176afbc28c937000ff585--nervous-villani-f8256d.netlify.app/problem_sets/problem_set_6) with binder, it launches an outdated notebook instead.

**Comment by mmcky** [comment]
@Alim-faraji the `publish` workflow doesn't run until you publish to `gh-pages` so I will merge this given this isn't `live` so you can test in the final configuration.

**Pull request merged**
