### PR TITLE
WIP: patch pandas issues and upgrades

### PR DESCRIPTION
**Pull request by doctor-phil**
This PR

- [x] patches `pandas` issues and upgrades
- [x] upgrades `environment.yml` to latest anaconda and software
- [x] updates `lectures` to run with the latest packages

this PR now includes #259

### CODE REVIEW

**Comment by mmcky** [comment]
@doctor-phil -- this is now running but with some errors re: code in the lectures.

**Comment by doctor-phil** [comment]
@mmcky thanks! I'll try to deal with the lecture build errors

**Comment by mmcky** [comment]
@doctor-phil could be some odd cache issue, however a few more execution issues have showed up

- [ ] (applications/networks.md) ValueError[0m: could not convert string to float: '2/1/2021'
- [ ] (applications/recidivism.md) ZeroDivisionError[0m: float division by zero
- [ ] (applications/working_with_text.md) 
    [0;31mValueError[0m: time data "2016-10-26T00:00:00Z" doesn't match format "%Y-%m-%dT%H:%M:%S.%f%z", at position 8659. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
- [ ] (problem_sets/problem_set_8.md) ValueError[0m: Value must be a nonnegative integer or None

**Comment by mmcky** [comment]
@doctor-phil I have merged the branch associated with #259 into this PR.

**Comment by mmcky** [comment]
@doctor-phil here is the latest set of errors:

[execution-reports-6.zip](https://github.com/user-attachments/files/17605800/execution-reports-6.zip)

**Pull request merged**
