### PR TITLE
Revert "Adding launch button settings"

### PR DESCRIPTION
**Pull request by AakashGfude**
Reverts QuantEcon/lecture-datascience.myst#66

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude this seems to be stalling when trying to resolve these `pip` dependencies. Perhaps there has been a version update which makes this set `unsolvable`

**Comment by mmcky** [comment]
@arnavs can you go through the `environment.yml` and migrate the `pip` packages that can be sourced from `conda` to be above `pip` in the listing. Otherwise we can put together a `requirements.txt` file instead and use `python` environment on `github actions` instead of `miniconda`

**Comment by mmcky** [comment]
@AakashGfude I think I have now pushed an update to `environment.yml` that will resolve. 

@arnavs we should still go through the exercise in another PR to reduce `pip` in favour of `conda` packages. Also `anaconda=2020.11` is installed so some of these may not be needed

**Comment by AakashGfude** [comment]
Thank you so much @mmcky , will merge this now.

**Comment by aadsouza** [comment]
@arnavs we had needed the `sphinxcontrib-bibtex` version to be pinned in order to get the citations and references working. see #9

**Comment by mmcky** [comment]
hey @aadsouza `jupyter-book` has now been updated to work with `sphinxcontrib-bibtex>=2.0`

https://github.com/executablebooks/jupyter-book/pull/1190

**Pull request merged**
